/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author JUAN JOSE
 */
public class I_prin_admin extends javax.swing.JFrame {

    /**
     * Creates new form I_prin_admin
     */
    public I_prin_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        Productos = new javax.swing.JMenu();
        Aprod = new javax.swing.JMenuItem();
        Bprod = new javax.swing.JMenuItem();
        Vender = new javax.swing.JMenu();
        Gfactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Prin_admin"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Boricuas sistem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        Productos.setText("Productos");

        Aprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/Product-documentation-icon.png"))); // NOI18N
        Aprod.setText("Agregar producto");
        Aprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprodActionPerformed(evt);
            }
        });
        Productos.add(Aprod);

        Bprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/search-icon.png"))); // NOI18N
        Bprod.setText("Buscar Producto");
        Bprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BprodActionPerformed(evt);
            }
        });
        Productos.add(Bprod);

        jMenuBar4.add(Productos);

        Vender.setText("Vender");

        Gfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/sale-icon.png"))); // NOI18N
        Gfactura.setText("Generar factura");
        Gfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GfacturaActionPerformed(evt);
            }
        });
        Vender.add(Gfactura);

        jMenuBar4.add(Vender);

        setJMenuBar(jMenuBar4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprodActionPerformed
        I_agregar_prod o=new I_agregar_prod();
        o.setVisible(rootPaneCheckingEnabled);
        this.hide();
    }//GEN-LAST:event_AprodActionPerformed

    private void BprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BprodActionPerformed
        I_buscar o=new I_buscar();
        o.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_BprodActionPerformed

    private void GfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GfacturaActionPerformed
        I_factur o=new I_factur();
        o.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_GfacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_prin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_prin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_prin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_prin_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_prin_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aprod;
    private javax.swing.JMenuItem Bprod;
    private javax.swing.JMenuItem Gfactura;
    private javax.swing.JMenu Productos;
    private javax.swing.JMenu Vender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
